server:
  port: 8098

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: client-updater
  #  config:
  #    import: "optional:configserver:"
  profiles:
    active: native
  data:
    mongodb:
      database: admin
#      username: admin
#      password: admin

feign:
  circuitbreaker:
    enabled: true