server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: client-service
#  config:
#    import: "optional:configserver:"
  profiles:
    active: native
  data:
    mongodb:
      database: admin
#      username: admin
#      password: admin
feign:
  circuitbreaker:
    enabled: true

Lospring:
  sleuth:
    sampler:
      probability: 2.0