server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: book-service
  config:
    import: "optional:configserver:"
  profiles:
    active: native
  data:
    mongodb:
      database: admin
#      username: admin
#      password: admin

Lospring:
  sleuth:
    sampler:
      probability: 2.0