spring:
  application:
    name: eureka-server
server:
  port: ${PORT:8761}
eureka:
  client:
    registerWithEureka: false # мы не хотим, чтобы наш сервер Eureka зарегистрировался сам с собой
    fetchRegistry: false # 1 не хотим получать информацию реестра от Eureka Server
    enabled: true # Включить/отключить регистрацию можно с помощью свойства:
    eureka-server-connect-timeout-seconds: 60 # 2 время ожидания (1 минута) до истечения тайм-аута соединения с Eureka Server
    eureka-service-url-poll-interval-seconds: 15 # 3 каждые 15 секунд запрашивать изменения об информации с сервера
    use-dns-for-fetching-service-urls: false # 4.1 запретите dns и укажите явный маршрут к серверам eureka (serviceUrl)
    prefer-same-zone-eureka: true # 6.1 использовать сервер eureka в той же зоне
    healthcheck:
      enabled: true # 7 для клиента включим healthcheck
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 4.2 запретите dns и укажите явный маршрут к серверам eureka (serviceUrl)

  server:
    renewal-percent-threshold: 0.85  # 5 если возникнут проблемы в сети или наш сервер выйдет из строя мы хотим запретить клиент

  instance:
    hostname: my-eureka-server.com # 4.3 запретите dns и укажите явный маршрут к серверам eureka (serviceUrl)
    metadata-map:
      zone: zone_A # 6.2 использовать сервер eureka в той же зоне
    lease-renewal-interval-in-seconds: 20 # 8 установить время, по которому сервер будет ожидать эхо запрос от клиента о том что он жив (20 секунд)
    lease-expiration-duration-in-seconds: 70 # 9 Если Eureka Server не видел обновления в течение 70 секунд, он удаляет экземпляр из своего реестра